#ifndef COMMON_COLORS_H_INCLUDED
#define COMMON_COLORS_H_INCLUDED

#define RED_CONSOLE "\033[31m"
#define BOLD_CONSOLE "\033[1m"
#define RESET_CONSOLE "\033[0m"

#endif /* COMMON_COLORS_H_INCLUDED */
